name: Docker CI/CD

on:
  push:
    branches: [ "master", "cicd-test" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config

#      # 2. 현재 시간 기반 이미지 태그 생성
#    - name: Generate timestamp tag
#      id: tag
#      run: |
#        echo "TAG=$(date '+%Y%m%d%H%M')" >> $GITHUB_ENV
#
#      # 3. Docker 이미지 빌드
#    - name: Build Docker Image
#      run: |
#        docker build --file Dockerfile -t hjproject.kro.kr/chatforyou/chatforyou:${{ env.TAG }} .
#
#      # 4. Docker 이미지 푸시
#    - name: Push Docker Image
#      run: |
#        docker push hjproject.kro.kr/chatforyou/chatforyou:${{ env.TAG }}
#
#      # 5. Kubernetes Kubeconfig 설정
#    - name: Configure Kubeconfig
#      run: |
#        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
#        export KUBECONFIG=$PWD/kubeconfig
#
#      # 6. Kubernetes 배포
#    - name: Deploy to Kubernetes
#      run: |
#        kubectl set image deployment/chatforyou-io \
#          chatforyou-container=hjproject.kro.kr/chatforyou/chatforyou:${{ env.TAG }} \
#          -n chatforyou-io
#        kubectl rollout status deployment/chatforyou-io -n chatforyou-io