name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    # 3. Docker 이미지 빌드
    - name: Build Docker Image
      run: |
        docker build --file Dockerfile -t hjproject.kro.kr/chatforyou:chatforyou-${{ github.sha }} .
    
    # 4. Docker 이미지 푸시
    - name: Push Docker Image
      run: |
        docker push hjproject.kro.kr/chatforyou:chatforyou-${{ github.sha }}
